blank_issues_enabled: false
contact_links:
  - name: 🙋🏽‍♀️ Getting help with code
    url: https://discord.gg/2mHUjKTq3K
    about: Get help with code-level questions on Discord.
  - name: 🙋 Getting general help
    url: https://discord.gg/2mHUjKTq3K
    about: Discord server
